load("@rules_cc//cc:defs.bzl", "cc_library")

filegroup(
    name = "shared_raw",
    srcs = ["@bazelrio_edu_wpi_first_ni-libraries_runtime_linuxathena//:shared"],
    visibility = ["@bzlmodrio-ni//:__subpackages__"],
)

cc_library(
    name = "shared",
    srcs = [":shared_raw"],
    target_compatible_with = select({
        "@rules_bzlmodrio_toolchains//constraints/is_roborio:roborio": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["@bzlmodrio-ni//:__subpackages__"],
    alwayslink = 1,
)
