load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# My repository!
local_repository(
    name = "bzlmodrio-ni",
    path = "../",
)

# Google Test
http_archive(
    name = "googletest",
    sha256 = "8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7",
    strip_prefix = "googletest-1.14.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz"],
)

load("@bzlmodrio-ni//private/non_bzlmod_dependencies:download_dependencies.bzl", "download_dependencies")

download_dependencies()

load("@bzlmodrio-ni//private/non_bzlmod_dependencies:setup_dependencies.bzl", "setup_dependencies")

setup_dependencies()

#####################
# Styleguide
#####################

http_archive(
    name = "rules_wpi_styleguide",
    sha256 = "b8215443ef1a6cc8170bc76203e44f22516614c58935e22c6a94b63656e2c88a",
    url = "https://github.com/bzlmodRio/rules_wpi_styleguide/releases/download/2024.11.19/rules_wpi_styleguide-2024.11.19.tar.gz",
)

load("@rules_wpi_styleguide//dependencies:load_rule_dependencies.bzl", "load_styleguide_rule_dependencies")

load_styleguide_rule_dependencies()

load("@rules_wpi_styleguide//dependencies:load_dependencies.bzl", "load_styleguide_dependencies")

load_styleguide_dependencies()

load("@rules_wpi_styleguide//dependencies:load_transitive_dependencies.bzl", "load_styleguide_transitive_dependencies")

load_styleguide_transitive_dependencies()

load("@rules_wpi_styleguide//dependencies:setup_styleguide.bzl", "setup_styleguide")

setup_styleguide()

load("@rules_wpi_styleguide//dependencies:load_pins.bzl", "load_styleguide_pins")

load_styleguide_pins()
#####################
